import path from "node:path";
import { commandExists } from "../project.js";
import { pathExists, readText } from "../io.js";
import { readTemplate } from "../templates.js";
import type { ClientStatus, InstallManifest } from "../types.js";
import type { ClientAdapter, ManagedPath } from "./client.js";
import { removeOwnedFile, writeOwnedFile } from "./shared.js";

const EXTENSION_PATH = ".pi/extensions/prolong.ts";

export class PiAdapter implements ClientAdapter {
  readonly name = "pi" as const;

  constructor(private readonly root: string, private readonly manifest: InstallManifest | null) {}

  async detect(): Promise<boolean> {
    return await commandExists("pi") || await pathExists(path.join(this.root, ".pi"));
  }

  async install(): Promise<ManagedPath[]> {
    const content = await readTemplate("clients/pi.ts");
    await writeOwnedFile(this.root, EXTENSION_PATH, content, this.manifest, "Generated by PRO-LONG");
    return [{ path: EXTENSION_PATH, mode: "owned" }];
  }

  async status(): Promise<ClientStatus> {
    const detected = await this.detect();
    const content = await readText(path.join(this.root, EXTENSION_PATH));
    const installed = content?.includes("Generated by PRO-LONG") === true;
    return {
      name: this.name,
      detected,
      installed,
      healthy: installed,
      detail: installed ? "project extension installed" : "project extension is missing",
    };
  }

  async uninstall(manifest: InstallManifest | null): Promise<string[]> {
    const warning = await removeOwnedFile(this.root, EXTENSION_PATH, manifest, await readTemplate("clients/pi.ts"));
    return warning === null ? [] : [warning];
  }
}
