// Generated by PRO-LONG. Re-run `prolong init` to update.
import { record } from "../../.prolong/runtime.mjs";

function safeRecord(event) {
  try {
    record("opencode", event);
  } catch {
    // Observability must not interrupt the user's coding session.
  }
}

export const ProlongPlugin = async ({ directory, worktree }) => ({
  event: async ({ event }) => {
    if (
      event.type === "session.created"
      || event.type === "session.idle"
      || event.type === "session.compacted"
      || event.type === "message.updated"
    ) {
      safeRecord({ ...event, cwd: directory, worktree });
    }
  },
  "tool.execute.before": async (input, output) => {
    safeRecord({
      type: "tool.execute.before",
      cwd: directory,
      worktree,
      input,
      toolInput: output.args,
    });
  },
  "tool.execute.after": async (input, output) => {
    safeRecord({
      type: "tool.execute.after",
      cwd: directory,
      worktree,
      input,
      output,
    });
  },
});
