// Generated by PRO-LONG. Re-run `prolong init` to update.
import { record } from "../../.prolong/runtime.mjs";

function safeRecord(event) {
  try {
    record("pi", event);
  } catch {
    // Observability must not interrupt the user's coding session.
  }
}

export default function prolong(pi) {
  pi.on("session_start", async (event, ctx) => {
    safeRecord({ ...event, type: "session_start", cwd: ctx.cwd });
  });
  pi.on("message_end", async (event, ctx) => {
    safeRecord({ ...event, type: "message_end", cwd: ctx.cwd });
  });
  pi.on("tool_execution_start", async (event, ctx) => {
    safeRecord({ ...event, type: "tool_execution_start", cwd: ctx.cwd });
  });
  pi.on("tool_execution_end", async (event, ctx) => {
    safeRecord({ ...event, type: "tool_execution_end", cwd: ctx.cwd });
  });
  pi.on("session_shutdown", async (event, ctx) => {
    safeRecord({ ...event, type: "session_shutdown", cwd: ctx.cwd });
  });
}
